database:
    type: "mongo"
    uri: "mongodb://localhost:27017"
    database: ""
    users-collection: "users"

moderation:
    defaultReason: "No reason given."

swearWords: ["funniwordsgohere"]

blockedWords: []

commands:
    # Enable if the plugin is loaded on a lobby server or equivalent
    limitedCommands: false