database:
    type: "mongo"
    uri: "mongodb://uxh5futzi56lapqpnupd:fQKxI8M4t32HxPiO2084@bvt9uk8itwhrlwe-mongodb.services.clever-cloud.com:27017/bvt9uk8itwhrlwe"
    database: "bvt9uk8itwhrlwe"
    users-collection: "users"

moderation:
    defaultReason: "No reason given."

joinQuit:
    joinMessage: "&8[&2&l+&8] &7%PLAYER%"
    quitMessage: "&8[&c&l-&8] &7%PLAYER%"

swearWords: ["funniwordsgohere"]

blockedWords: []

links:
    rules: "https://pixlies.net/rules"
    discord: "https://pixlies.net/discord"

chat:
    formatting: true

commands:
    # Enable if the plugin is loaded on a lobby server or equivalent
    limitedCommands: false