database:
    type: "mongo"
    uri: "mongodb://localhost:27017"
    database: ""
    users-collection: "users"

moderation:
    defaultReason: "No reason given."

joinQuit:
    joinMessage: "&8[&2&l+&8] &7%PLAYER%"
    quitMessage: "&8[&c&l-&8] &7%PLAYER%"

swearWords: ["funniwordsgohere"]

blockedWords: []

commands:
    # Enable if the plugin is loaded on a lobby server or equivalent
    limitedCommands: false