database:
    type: "mongo"
    uri: "mongodb://localhost:27017"
    database: ""
    users-collection: "users"

moderation:
    defaultReason: "No reason given."

swearWords: ["funniwordsgohere"]

blockedWords: